// <auto-generated />
using System;
using Dadekavan.EntityFrameworkCore.DadekavanDbContextApplication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dadekavan.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(DadekavanDbContext))]
    partial class DadekavanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dadekavan.Domain.Entity.Flight", b =>
                {
                    b.Property<int>("flight_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("flight_id"));

                    b.Property<byte>("airline_id")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("arrival_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("departure_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("route_id")
                        .HasColumnType("int");

                    b.HasKey("flight_id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Dadekavan.Domain.Entity.Route", b =>
                {
                    b.Property<int>("route_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("route_id"));

                    b.Property<DateTime>("departure_date")
                        .HasColumnType("datetime2");

                    b.Property<short>("destination_city_id")
                        .HasColumnType("smallint");

                    b.Property<short>("origin_city_id")
                        .HasColumnType("smallint");

                    b.HasKey("route_id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Dadekavan.Domain.Entity.Subscription", b =>
                {
                    b.Property<byte>("agency_id")
                        .HasColumnType("tinyint");

                    b.Property<short>("destination_city_id")
                        .HasColumnType("smallint");

                    b.Property<short>("origin_city_id")
                        .HasColumnType("smallint");

                    b.HasKey("agency_id");

                    b.ToTable("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
